dev.host=https://c23dbda7trial.it-cpitrial06.cfapps.us10-001.hana.ondemand.com
dev.token.url=https://c23dbda7trial.authentication.us10.hana.ondemand.com/oauth/token
dev.client.id=sb-4eb59527-1de0-405e-8ebf-60f3017b2a97!b667225|it!b55215
dev.client.secret=b1f99b31-fb95-4d95-90fb-4895695166d8$SkxEaIqE9TfHSHncfyHzsoEPwj7mEIWyOBYLzskN3YE=
integration.api.url=/api/v1



qa.host=https://72143823trial.it-cpitrial05.cfapps.us10-001.hana.ondemand.com
qa.token.url=https://72143823trial.authentication.us10.hana.ondemand.com/oauth/token
qa.client.id=sb-39f2a3a5-20d3-4667-adef-8d30d962b310!b677634|it!b26655
qa.client.secret=c236b643-9959-4306-9377-9243072f8074$VQUflZt53kuybQCo3hLF2jZzVrtpM47uQbBX35N1fpM=