integration.host=https://c23dbda7trial.it-cpitrial06.cfapps.us10-001.hana.ondemand.com
integration.token.url=https://c23dbda7trial.authentication.us10.hana.ondemand.com/oauth/token
integration.client.id=sb-4eb59527-1de0-405e-8ebf-60f3017b2a97!b667225|it!b55215
integration.client.secret=b1f99b31-fb95-4d95-90fb-4895695166d8$SkxEaIqE9TfHSHncfyHzsoEPwj7mEIWyOBYLzskN3YE=
integration.api.url=/api/v1